CREATE TABLE public.excursion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT excursion_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE public.excursion
    OWNER to postgres;

CREATE TABLE public.autors
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 5 ),
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT autors_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE public.autors
    OWNER to postgres;

CREATE TABLE public.audiences
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT audience_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE public.audiences
    OWNER to postgres;

CREATE TABLE public.exhibits
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    material character varying(30) COLLATE pg_catalog."default",
    techic character varying(30) COLLATE pg_catalog."default",
    audience_id bigint,
    name character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT exhibits_pkey PRIMARY KEY (id),
    CONSTRAINT audience FOREIGN KEY (audience_id)
        REFERENCES public.audiences (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

    TABLESPACE pg_default;

ALTER TABLE public.exhibits
    OWNER to postgres;

CREATE TABLE public.autor_exhibit
(
    autor_id bigint NOT NULL,
    exhibit_id bigint NOT NULL,
    CONSTRAINT autor_exhibit_pkey PRIMARY KEY (autor_id, exhibit_id),
    CONSTRAINT exhibit_id FOREIGN KEY (exhibit_id)
        REFERENCES public.exhibits (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

    TABLESPACE pg_default;

ALTER TABLE public.autor_exhibit
    OWNER to postgres;

CREATE TABLE public.employees
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    login character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    audience_id bigint,
    CONSTRAINT employees_pkey PRIMARY KEY (id),
    CONSTRAINT audience FOREIGN KEY (audience_id)
        REFERENCES public.audiences (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

    TABLESPACE pg_default;

ALTER TABLE public.employees
    OWNER to postgres;

CREATE TABLE public.timetable
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    employee_id bigint NOT NULL,
    excursion_id bigint NOT NULL,
    date_start timestamp with time zone NOT NULL,
    date_end timestamp with time zone NOT NULL,
    CONSTRAINT timetable_pkey PRIMARY KEY (id),
    CONSTRAINT employee FOREIGN KEY (employee_id)
        REFERENCES public.employees (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT excursion_id FOREIGN KEY (excursion_id)
        REFERENCES public.excursion (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

    TABLESPACE pg_default;

ALTER TABLE public.timetable
    OWNER to postgres;

